version: "3.8"
services:
  chrome-extension:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"